server.port: 8080

apiservice:
  send-topics: tracing-consumers
  reply-topics: tracing-consumers-reply
  consumer-group: tracing-grafana

spring:
  kafka:
    bootstrap-servers: kafka:29092
  output:
    ansi:
      enabled: always
  application:
    name: api-service

management:
  endpoint:
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include: beans