server.port: 8080

addressClient:
  baseUrl: http://customer-service:8081

customerClient:
  baseUrl: http://customer-service:8081

spring:
  output:
    ansi:
      enabled: always
  application:
    name: api-service          

logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  endpoint:
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling.probability: 1.0
    
otel.exporter.otlp.traces.endpoint: http://collector:4317